// <auto-generated />
using System;
using FactoryIoT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FactoryIoT.Infrastructure.Migrations
{
    [DbContext(typeof(FactoryIoTDbContext))]
    [Migration("20260727090000_TieredStorage")]
    partial class TieredStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FactoryIoT.Domain.Entities.MachineSummary", b =>
                {
                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("MaxPressure")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MinPressure")
                        .HasColumnType("float");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint");

                    b.Property<double>("SumPressure")
                        .HasColumnType("float");

                    b.Property<double>("SumTemperature")
                        .HasColumnType("float");

                    b.HasKey("MachineId");

                    b.ToTable("MachineSummaries");
                });

            modelBuilder.Entity("FactoryIoT.Domain.Entities.RollupCheckpoint", b =>
                {
                    b.Property<int>("Granularity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("LastCompletedBucketStart")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Granularity");

                    b.ToTable("RollupCheckpoints");
                });

            modelBuilder.Entity("FactoryIoT.Domain.Entities.SensorReading", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Timestamp", "Id");

                    b.HasIndex("MachineId", "Timestamp")
                        .IsDescending(false, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("MachineId", "Timestamp"), new[] { "SensorType", "Value", "Unit" });

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("FactoryIoT.Domain.Entities.Telemetry", b =>
                {
                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Pressure")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("Timestamp", "Id");

                    b.HasIndex("MachineId", "Timestamp")
                        .IsDescending(false, true);

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("MachineId", "Timestamp"), new[] { "Temperature", "Pressure", "Status" });

                    b.ToTable("Telemetries");
                });

            modelBuilder.Entity("FactoryIoT.Domain.Entities.TelemetryRollup", b =>
                {
                    b.Property<int>("Granularity")
                        .HasColumnType("int");

                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("FirstReading")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastReading")
                        .HasColumnType("datetimeoffset");

                    b.Property<double>("MaxPressure")
                        .HasColumnType("float");

                    b.Property<double>("MaxTemperature")
                        .HasColumnType("float");

                    b.Property<double>("MinPressure")
                        .HasColumnType("float");

                    b.Property<double>("MinTemperature")
                        .HasColumnType("float");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<double>("SumPressure")
                        .HasColumnType("float");

                    b.Property<double>("SumTemperature")
                        .HasColumnType("float");

                    b.HasKey("Granularity", "MachineId", "BucketStart");

                    b.HasIndex("Granularity", "BucketStart");

                    b.ToTable("TelemetryRollups");
                });

            modelBuilder.Entity("FactoryIoT.Domain.Entities.TelemetryStatusRollup", b =>
                {
                    b.Property<int>("Granularity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("BucketStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MachineId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("Granularity", "BucketStart", "MachineId", "Status");

                    b.ToTable("TelemetryStatusRollups");
                });
#pragma warning restore 612, 618
        }
    }
}
